import type { CarrierOffer, Load } from './types'

export const loads: Load[] = [
  {
    id: '11436778',
    po: 'PO-88421',
    mode: 'Spot',
    modeDetail: 'Power Only',
    status: 'NeedCarrier',
    stage: 'Sourcing',
    subStage: 'Overview',
    customer: 'Honda North America',
    equipment: 'DRY-VAN',
    origin: 'Marysville, OH',
    destination: 'Detroit, MI',
    miles: 186,
    pickup: 'Jul 14 · 08:00',
    delivery: 'Jul 14 · 18:00',
    team: 'Ohio',
  },
  {
    id: '11440520',
    po: 'PO-99102',
    mode: 'Expedited',
    modeDetail: 'Hot Shot',
    status: 'NeedCarrier',
    stage: 'Sourcing',
    subStage: 'Find & Post',
    customer: 'Nova Chemicals Corporation',
    equipment: 'FLATBED',
    origin: 'Sarnia, ON',
    destination: 'Houston, TX',
    miles: 1818,
    pickup: 'Jul 13 · 14:30',
    delivery: 'Jul 16 · 09:00',
    rate: '$9.25',
  },
  {
    id: '11402376',
    po: 'Test_12Sept',
    mode: 'Spot',
    modeDetail: 'Pure Brokerage',
    status: 'Posted',
    stage: 'Tender',
    subStage: 'Offers & Bids',
    customer: 'Dollar Tree',
    equipment: 'DRY-VAN',
    origin: 'Brampton, ON',
    destination: 'Brampton, ON',
    miles: 12,
    pickup: 'Jun 12 · 11:30',
    delivery: 'Jun 13 · 11:30',
    team: 'Ontario',
  },
  {
    id: '11441288',
    po: 'PO-77210',
    mode: 'Managed',
    modeDetail: 'Contract',
    status: 'Covered',
    stage: 'Booking',
    subStage: 'Resources',
    customer: 'Phillips Industries',
    equipment: 'REEFER',
    origin: 'Chicago, IL',
    destination: 'Atlanta, GA',
    miles: 716,
    pickup: 'Jul 15 · 06:00',
    delivery: 'Jul 16 · 16:00',
    team: 'Midwest',
    broker: 'CGL Desk',
  },
  {
    id: '11439801',
    po: 'PO-55019',
    mode: 'Spot',
    modeDetail: 'Power Only',
    status: 'NeedCarrier',
    stage: 'Sourcing',
    subStage: 'Overview',
    customer: 'Procter & Gamble',
    equipment: 'DRY-VAN',
    origin: 'Cincinnati, OH',
    destination: 'Nashville, TN',
    miles: 273,
    pickup: 'Jul 14 · 10:00',
    delivery: 'Jul 14 · 22:00',
    team: 'Tennessee',
  },
  {
    id: '11440155',
    po: 'PO-33088',
    mode: 'Spot',
    modeDetail: 'Brokerage',
    status: 'Covered',
    stage: 'Booking',
    subStage: 'Send Confirmation',
    customer: 'Home Depot',
    equipment: 'INTERMODAL',
    origin: 'Dallas, TX',
    destination: 'Phoenix, AZ',
    miles: 887,
    pickup: 'Jul 13 · 07:00',
    delivery: 'Jul 15 · 12:00',
    broker: 'Southwest',
  },
  {
    id: '11438992',
    po: 'PO-11990',
    mode: 'Expedited',
    modeDetail: 'Team',
    status: 'NeedCarrier',
    stage: 'Award',
    subStage: 'CMT',
    customer: 'Tesla Energy',
    equipment: 'FLATBED',
    origin: 'Fremont, CA',
    destination: 'Austin, TX',
    miles: 1756,
    pickup: 'Jul 14 · 05:00',
    delivery: 'Jul 16 · 20:00',
    rate: '↘ $345',
  },
  {
    id: '11437640',
    po: 'PO-44120',
    mode: 'Managed',
    modeDetail: 'Dedicated',
    status: 'Posted',
    stage: 'Tender',
    subStage: 'Finalize Tender',
    customer: 'Walmart Logistics',
    equipment: 'DRY-VAN',
    origin: 'Bentonville, AR',
    destination: 'Memphis, TN',
    miles: 292,
    pickup: 'Jul 15 · 09:00',
    delivery: 'Jul 15 · 18:00',
    team: 'South',
  },
  {
    id: '11442011',
    po: 'PO-88200',
    mode: 'Spot',
    modeDetail: 'Pure Brokerage',
    status: 'NeedCarrier',
    stage: 'Sourcing',
    subStage: 'Find & Post',
    customer: 'Unilever Canada',
    equipment: 'REEFER',
    origin: 'Toronto, ON',
    destination: 'Montreal, QC',
    miles: 337,
    pickup: 'Jul 14 · 11:00',
    delivery: 'Jul 15 · 08:00',
  },
  {
    id: '11441567',
    po: 'PO-22991',
    mode: 'Spot',
    modeDetail: 'Power Only',
    status: 'Covered',
    stage: 'Booking',
    subStage: 'Signed Confirmation',
    customer: 'Costco Wholesale',
    equipment: 'DRY-VAN',
    origin: 'Seattle, WA',
    destination: 'Portland, OR',
    miles: 174,
    pickup: 'Jul 13 · 13:00',
    delivery: 'Jul 13 · 19:00',
    team: 'Pacific',
  },
  {
    id: '11440890',
    po: 'PO-67001',
    mode: 'Managed',
    modeDetail: 'Contract',
    status: 'NeedCarrier',
    stage: 'Award',
    subStage: 'Finalize Carrier Award',
    customer: 'Amazon Fulfillment',
    equipment: 'DRY-VAN',
    origin: 'Allentown, PA',
    destination: 'Baltimore, MD',
    miles: 168,
    pickup: 'Jul 14 · 16:00',
    delivery: 'Jul 15 · 06:00',
  },
  {
    id: '11439234',
    po: 'PO-10355',
    mode: 'Spot',
    modeDetail: 'Brokerage',
    status: 'NeedCarrier',
    stage: 'Sourcing',
    subStage: 'Overview',
    customer: 'Nestlé Waters',
    equipment: 'DRY-VAN',
    origin: 'Dallas, TX',
    destination: 'Kansas City, MO',
    miles: 502,
    pickup: 'Jul 15 · 08:30',
    delivery: 'Jul 16 · 14:00',
    team: 'Central',
  },
]

export const offers: CarrierOffer[] = [
  {
    id: '1',
    name: '1354943 Ontario Inc',
    mc: 'MC-884291',
    dot: 'DOT-3129981',
    bid: '$0.93',
    vsTarget: '−$0.07 vs Target',
    vsTargetTone: 'good',
    rank: 'BEST',
    status: 'PENDING',
  },
  {
    id: '2',
    name: 'TransCanada Freight Ltd',
    mc: 'MC-552101',
    dot: 'DOT-1988220',
    bid: '$1.05',
    vsTarget: '+$0.05 vs Target',
    vsTargetTone: 'warn',
    rank: 'HIGH',
    status: 'PENDING',
  },
  {
    id: '3',
    name: 'Midwest Haulers LLC',
    mc: 'MC-771234',
    dot: 'DOT-4451209',
    bid: '$0.88',
    vsTarget: '−$0.12 vs Target',
    vsTargetTone: 'good',
    rank: 'LOW',
    status: 'EXPIRED',
  },
  {
    id: '4',
    name: 'Blue Corridor Express',
    mc: 'MC-229910',
    dot: 'DOT-8871200',
    bid: '$1.12',
    vsTarget: '+$0.12 vs Target',
    vsTargetTone: 'warn',
    status: 'REJECTED',
  },
  {
    id: '5',
    name: 'Northline Logistics',
    mc: 'MC-110288',
    dot: 'DOT-5566123',
    bid: '$0.97',
    vsTarget: '−$0.03 vs Target',
    vsTargetTone: 'good',
    status: 'OFFERED',
  },
]

export const modeCounts = {
  All: 8672,
  Spot: 8517,
  Expedited: 24,
  Managed: 131,
} as const

export const statusCounts = {
  All: 8672,
  NeedCarrier: 6477,
  Posted: 61,
  Covered: 2134,
} as const

export const stageNav = [
  {
    stage: 'Sourcing' as const,
    count: 3564,
    items: [
      { label: 'Overview', count: 2102 },
      { label: 'Find & Post', count: 1462 },
    ],
  },
  {
    stage: 'Tender' as const,
    count: 63,
    items: [
      { label: 'Offers & Bids', count: 41 },
      { label: 'Finalize Tender', count: 22 },
    ],
  },
  {
    stage: 'Award' as const,
    count: 20,
    items: [
      { label: 'CMT', count: 12 },
      { label: 'Finalize Carrier Award', count: 8 },
    ],
  },
  {
    stage: 'Booking' as const,
    count: 5025,
    items: [
      { label: 'Create Contract', count: 890 },
      { label: 'Send Confirmation', count: 1204 },
      { label: 'Signed Confirmation', count: 1580 },
      { label: 'Resources', count: 1351 },
    ],
  },
]

export const offerStatusFilters = [
  { label: 'All', count: 253 },
  { label: 'Pending', count: 35 },
  { label: 'Offered', count: 1 },
  { label: 'Countered', count: 5 },
  { label: 'Accepted', count: 3 },
  { label: 'Rejected', count: 43 },
  { label: 'Expired', count: 151 },
  { label: 'Contract Created', count: 11 },
]

export const quickReplies = [
  'Can you do $2,500 all-in?',
  "What's your earliest pickup?",
  'Please share MC & insurance.',
  'Confirm empty miles.',
]
